### ISSUE TITLE
seeing some syntax error in seconds

### ISSUE THREAD

**Issue by kalyanakarthikeyan** [fvgs/litetimer#1]
i am not sure whether it is to me only - i am getting the syntax error as below 
```
module.exports = async seconds => {
                       ^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\litetimer\src\index.js:2:14)
```

Steps did -

npm install -g litetimer
then ran t 30s

**Comment by Eddykasp** [comment]
I'm getting the same error using node v6.11.0 on Ubuntu

**Comment by fvgs** [comment]
Thanks for bringing this up!

The error is due to running an old version of Node. Specifically, the version of Node does not support [async functions](http://node.green/#ES2017-features-async-functions). Async functions have been supported since Node 7.6.0.

There are several ways to solve this, including [installing the latest version of Node](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions), using npx, or using nvm.

I'll also refer you to the current [release schedule](https://github.com/nodejs/Release#release-schedule):

![image](https://user-images.githubusercontent.com/9427813/35404768-11bbc096-01d2-11e8-95d2-459144b4fc0a.png)
